### ISSUE TITLE
Use of plain text skill and trait names

### ISSUE THREAD

**Issue by chopfitzroy** [discretize/discretize-guides#1081]
I was looking through the guides and noticed in some places the plain text version of a skill name is [used](https://github.com/discretize/discretize-guides/blob/master/builds/ranger/condi-soulbeast/index.md?plain=1#L37) i.e:

```mdx
<Skill name="We heal as one"/>
```

Looking at [#241](https://github.com/discretize/discretize-guides/issues/241) I found [discretize.eu/editor/ids](https://discretize.eu/editor/ids ) which looks like it has all the values bundled into the JS loaded on the page.

I could not find any reference to the list of plain text values in any of the public repo's (which is totally fine).

I was hoping you could confirm that the `Skill` component used in the `*.md` files is a private component which references a private list of those plain text values and that it is not publicly available (primarily so I can stop looking for it).

**Comment by marcustyphoon** [comment]
I'll let Princeps or another person who works on this code more often than I do answer for sure, but I believe so, yes. The code in question is currently, um, not exactly, um... I wouldn't want to subject the public to it without some refactoring :D

**Comment by chopfitzroy** [comment]
Thanks so much for the response and appreciate the transparency. Good to know that it may be made publicly available in the future!

**Comment by gw2princeps** [comment]
Hey! 

Yes, your assumption is correct. 

We wrote a remark plugin that runs serversided and replaces the `name` prop with an id prop. If you can figure out how to traverse the AST, it should be fairly easy to accomplish. 

Some pointers (didnt test if it actually runs): 

```js
export default (options = {}) => {
  return (markdownAST) => {
    const gw2uitypes = ['Skill', 'Trait', 'Item'];

    visit(markdownAST, (node) => {
      let componentType = node.name;

      if (gw2uitypes.includes(componentType)) {
        const id = resolve(node) // blackbox function, which resolves the id based on the given props

        node.attributes = [
          ...node.attributes,
          { type: 'mdxJsxAttribute', name: 'id', value: id },
        ];
      }
    });
    return markdownAST;
  };
};
```

Cheers!

**Comment by chopfitzroy** [comment]
Hey @gw2princeps thanks so much this response really appreciate you taking the time!!!

That all sounds really achievable and I appreciate the pointers <3
