### ISSUE TITLE
Cheat Sheet

### ISSUE THREAD

**Issue by Janitsu** [discretize/discretize-guides#522]
In the cheat sheet, it says that you want Impact sigil for Twilight Oasis but does Amala ever get stunned actually? If not, shouldn't it follow the same default option of Air sigil (looking at Deepstone for example)?

Molten Furnace says to drop Force sigil for Air, but I think it's meant to be Impact for Air.

Also, Chaos Isles is now only called Chaos in the game (despite references to it as the "Chaos Isles").

Snowblind you can use slaying potions and sigils for the first few elementals if you wanted to min-max, I am not sure what their exact race is (wiki says Icebrood).

Siren's Reef → Do ghost slaying potions and sigils work?
Aquatic Ruins → Are Scarlet slaying pots better than Sharpening Stones on power classes? Krait sigils are the same damage against boss as Impact sigils so that's understandable, but I am not sure if Scarlet Army pots are worth it.

Also fixed a typo in the cheat sheet.

**Comment by Janitsu** [comment]
#523 

typo fix

**Comment by SpatiumPrinceps** [comment]
Thanks for your service :peepopray:
